import Cosmo1 from '../assets/img/Portfolio/Cosmonauta/cosmo1.jpg'
import Cosmo2 from '../assets/img/Portfolio/Cosmonauta/cosmo2.jpg'
import Cosmo3 from '../assets/img/Portfolio/Cosmonauta/cosmo3.jpg'
import Cosmo4 from '../assets/img/Portfolio/Cosmonauta/cosmo4.jpg'
import Cosmo5 from '../assets/img/Portfolio/Cosmonauta/cosmo5.jpg'
import Cosmo6 from '../assets/img/Portfolio/Cosmonauta/cosmo6.jpg'
import Flora1 from '../assets/img/Portfolio/Flora/flora1.jpg'
import Flora2 from '../assets/img/Portfolio/Flora/flora2.jpg'
import Flora3 from '../assets/img/Portfolio/Flora/flora3.jpg'
import Flora4 from '../assets/img/Portfolio/Flora/flora4.jpg'
import Flora5 from '../assets/img/Portfolio/Flora/flora5.jpg'
import Flora6 from '../assets/img/Portfolio/Flora/flora6.jpg'
import Libreras1 from '../assets/img/Portfolio/Libreras/libreras1.jpg'
import Libreras2 from '../assets/img/Portfolio/Libreras/libreras2.jpg'
import Libreras3 from '../assets/img/Portfolio/Libreras/libreras3.jpg'
import Libreras4 from '../assets/img/Portfolio/Libreras/libreras4.jpg'
import Libreras5 from '../assets/img/Portfolio/Libreras/libreras5.jpg'
import Libreras6 from '../assets/img/Portfolio/Libreras/libreras6.jpg'
import Flotilla1 from '../assets/img/Portfolio/Flotilla/flotilla1.jpg'
import Flotilla2 from '../assets/img/Portfolio/Flotilla/flotilla2.jpg'
import Flotilla3 from '../assets/img/Portfolio/Flotilla/flotilla3.jpg'
import Flotilla4 from '../assets/img/Portfolio/Flotilla/flotilla4.jpg'
import Flotilla5 from '../assets/img/Portfolio/Flotilla/flotilla5.jpg'
import Flotilla6 from '../assets/img/Portfolio/Flotilla/flotilla6.jpg'
import Asocove1 from '../assets/img/Portfolio/Asocove/asocove1.jpg'
import Asocove2 from '../assets/img/Portfolio/Asocove/asocove2.jpg'
import Asocove3 from '../assets/img/Portfolio/Asocove/asocove3.jpg'
import Asocove4 from '../assets/img/Portfolio/Asocove/asocove4.jpg'
import Asocove5 from '../assets/img/Portfolio/Asocove/asocove5.jpg'
import Asocove6 from '../assets/img/Portfolio/Asocove/asocove6.jpg'
import Busquedas1 from '../assets/img/Portfolio/Busquedas/busquedas1.jpg'
import Busquedas2 from '../assets/img/Portfolio/Busquedas/busquedas2.jpg'
import Busquedas3 from '../assets/img/Portfolio/Busquedas/busquedas3.jpg'
import Busquedas4 from '../assets/img/Portfolio/Busquedas/busquedas4.jpg'
import Busquedas5 from '../assets/img/Portfolio/Busquedas/busquedas5.jpg'
import Busquedas6 from '../assets/img/Portfolio/Busquedas/busquedas6.jpg'
import Mura1 from '../assets/img/Portfolio/Mura/mura1.jpg'
import Mura2 from '../assets/img/Portfolio/Mura/mura2.jpg'
import Mura3 from '../assets/img/Portfolio/Mura/mura3.jpg'
import Mura4 from '../assets/img/Portfolio/Mura/mura4.jpg'
import Mura5 from '../assets/img/Portfolio/Mura/mura5.jpg'
import Mura6 from '../assets/img/Portfolio/Mura/mura6.jpg'


export const galleryCosmo = [Cosmo1, Cosmo2, Cosmo3, Cosmo4, Cosmo5, Cosmo6];
export const galleryFlotilla = [Flotilla1, Flotilla2, Flotilla3, Flotilla4, Flotilla5, Flotilla6];
export const galleryFlora = [Flora1, Flora2, Flora3, Flora4, Flora5, Flora6];
export const galleryLibreras = [Libreras1, Libreras2, Libreras3, Libreras4, Libreras5, Libreras6];
export const galleryAsocove = [Asocove1, Asocove2, Asocove3, Asocove4, Asocove5, Asocove6];
export const galleryBusquedas = [Busquedas1, Busquedas2, Busquedas3, Busquedas4, Busquedas5, Busquedas6];
export const galleryMura = [Mura1, Mura2, Mura3, Mura4, Mura5, Mura6];