services:

  # Servicio del Backend (Python/Flask API)
  server:
    build:
      context: . # El contexto es la raíz, donde están todos los archivos
      dockerfile: Dockerfile.backend # Especifica qué Dockerfile usar
    restart: always
    volumes:
      - ./src:/app
      - ./migrations:/app/migrations
    env_file: ./.env
    ports:
      - "8001:8000" # Maps Host 8001 to Flask 8000
    networks:
      - app-network
    depends_on:
      - db

  # Servicio del Frontend (React/Vite App)
  client:
    build:
      context: .
      dockerfile: Dockerfile.frontend # Especifica el otro Dockerfile
    restart: always
    ports:
      - "8002:80" # Maps Host 8002 to React's Nginx 80
    networks:
      - app-network

  # Servicio de la Base de Datos (PostgreSQL)
  db:
    image: postgres:14-alpine
    restart: always
    env_file: ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
