"""Update `lead` table columns

Revision ID: 5f9ce19115e9
Revises: d1354f2c617a
Create Date: 2026-08-19 01:08:22.103796

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5f9ce19115e9'
down_revision = 'd1354f2c617a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('lead', schema=None) as batch_op:

        batch_op.add_column(sa.Column('needs', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('stage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('problem_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ideal_timeframe', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('project_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('newsletter_opt_in', sa.Boolean(), nullable=False))

        batch_op.alter_column('phone',
            existing_type=sa.VARCHAR(length=15),
            type_=sa.String(length=30),
            nullable=True
        )

        batch_op.drop_constraint('lead_email_key', type_='unique')
        batch_op.drop_constraint('lead_phone_key', type_='unique')

        batch_op.drop_column('company')
        batch_op.drop_column('name')
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('lead', schema=None) as batch_op:

        batch_op.add_column(sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

        batch_op.create_unique_constraint('lead_phone_key', ['phone'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint('lead_email_key', ['email'], postgresql_nulls_not_distinct=False)

        batch_op.alter_column('phone',
            existing_type=sa.String(length=30),
            type_=sa.VARCHAR(length=15),
            nullable=False
        )

        batch_op.drop_column('newsletter_opt_in')
        batch_op.drop_column('project_name')
        batch_op.drop_column('full_name')
        batch_op.drop_column('ideal_timeframe')
        batch_op.drop_column('problem_description')
        batch_op.drop_column('stage')
        batch_op.drop_column('needs')

    # ### end Alembic commands ###
